### ISSUE TITLE
Cambios

### ISSUE THREAD

**Issue by fedm4** [florenxiagrasso/html17#1]
- [x] Sacar el estilo inline del body, y ponerlo en el css.
- [x] Sacar el div y los labels que no son necesarios.
- [x] El form deberia tener una clase que defina el cuadro. Para esto hace falta ```width: 360px; background: white;box-sizing:border-box; padding:45px;margin: 0 auto;```
- [x] Borrar la clase .label del css
- [x] En la clase .comun, deberia tener un ```width: 100%.``` Para que esto funcione necesitamos que ademas tenga el``` box-sizing: border-box;``` Ademas hay que sacar los margenes.
- [x] Deberiamos tener una clase para los inputs que le defina ```margin-bottom: 15px;``` y Ademas el ```background: #f2f2f2;```. 
- [x] La clase .button no deberia tener width ni height sino que deberia tomarlo de la clase .comun. Tampoco padding ni margin. Solo con background color y color de fuente estaria bien.

**Comment by florenxiagrasso** [comment]
Hice los cambios y los tildé. El primero - display: in-line block - ya estaba en el archivo .css asi que no entendi cual era el cambio que habia que hacer y los demas ahora estan bien!

**Comment by fedm4** [comment]
El primero es sacar el estilo  ``` <body style="background-color: #76b852">``` y pasar ese background-color al archivo.

**Comment by florenxiagrasso** [comment]
Listo!
